{% set name = "pyinaturalist" %}
{% set version = "0.17.0" %}
{% set hash_val = "c7cc2caad5a6f30f89822399333bdadcf902d901b34f93a829e7266ff34ab70a" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - poetry
    - pip
  run:
    - python >=3.7
    - attrs >=21.2
    - keyring >=22.3
    - platformdirs >=2.5
    - python-dateutil >=2.0
    - python-forge >=18.6
    - requests >=2.25
    - requests-cache >=1.0
    - requests-ratelimiter >=0.3.2
    - rich >=10.0

test:
  imports:
    - pyinaturalist
    - pyinaturalist.controllers
    - pyinaturalist.docs
    - pyinaturalist.models
    - pyinaturalist.v0
    - pyinaturalist.v1
    - pyinaturalist.v2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/niconoe/pyinaturalist
  summary: Python API client for iNaturalist
  license: MIT
  license_file: LICENSE
  doc_url: https://pyinaturalist.readthedocs.io/
  dev_url: https://github.com/niconoe/pyinaturalist

extra:
  recipe-maintainers:
    - jwcook
